--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-26-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_PLANNER_BOARD
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_PLANNER_BOARD" 
   (	"PB_NO" NUMBER, 
	"PB_P_NO" NUMBER, 
	"PB_M_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"PB_TITLE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"PB_CREATED_AT" DATE DEFAULT sysdate, 
	"PB_UPDATED_AT" DATE DEFAULT sysdate, 
	"PB_READ_COUNT" NUMBER DEFAULT 0, 
	"PB_CONTENT" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("PB_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ADMIN.TMI_PLANNER_BOARD
SET DEFINE OFF;
Insert into ADMIN.TMI_PLANNER_BOARD (PB_NO,PB_P_NO,PB_M_EMAIL,PB_TITLE,PB_CREATED_AT,PB_UPDATED_AT,PB_READ_COUNT) values (67,463,'ym1234@naver.com','부천으로 놀러오세요',to_date('22/08/25','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),6);
Insert into ADMIN.TMI_PLANNER_BOARD (PB_NO,PB_P_NO,PB_M_EMAIL,PB_TITLE,PB_CREATED_AT,PB_UPDATED_AT,PB_READ_COUNT) values (33,272,'ym1234@naver.com','플래너 테스트 원투쓰리',to_date('22/08/20','RR/MM/DD'),to_date('22/08/20','RR/MM/DD'),9);
Insert into ADMIN.TMI_PLANNER_BOARD (PB_NO,PB_P_NO,PB_M_EMAIL,PB_TITLE,PB_CREATED_AT,PB_UPDATED_AT,PB_READ_COUNT) values (73,475,'danji@naver.com','여름엔 강원도로! 1박2일',to_date('22/08/25','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),2);
Insert into ADMIN.TMI_PLANNER_BOARD (PB_NO,PB_P_NO,PB_M_EMAIL,PB_TITLE,PB_CREATED_AT,PB_UPDATED_AT,PB_READ_COUNT) values (71,461,'ym1234@naver.com','홍대로 놀러오세요',to_date('22/08/25','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),1);
Insert into ADMIN.TMI_PLANNER_BOARD (PB_NO,PB_P_NO,PB_M_EMAIL,PB_TITLE,PB_CREATED_AT,PB_UPDATED_AT,PB_READ_COUNT) values (63,426,'ym1234@naver.com','나의 멋진 플래너',to_date('22/08/22','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),9);
Insert into ADMIN.TMI_PLANNER_BOARD (PB_NO,PB_P_NO,PB_M_EMAIL,PB_TITLE,PB_CREATED_AT,PB_UPDATED_AT,PB_READ_COUNT) values (72,473,'danji@naver.com','제주도여행 일정 1박2일',to_date('22/08/25','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),3);
Insert into ADMIN.TMI_PLANNER_BOARD (PB_NO,PB_P_NO,PB_M_EMAIL,PB_TITLE,PB_CREATED_AT,PB_UPDATED_AT,PB_READ_COUNT) values (64,418,'honggd@naver.com','새로운 플래너',to_date('22/08/25','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),2);
--------------------------------------------------------
--  DDL for Index PK_PB_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_PB_NO" ON "ADMIN"."TMI_PLANNER_BOARD" ("PB_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_PLANNER_BOARD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD" MODIFY ("PB_P_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD" MODIFY ("PB_M_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD" ADD CONSTRAINT "PK_PB_NO" PRIMARY KEY ("PB_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_PLANNER_BOARD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD" ADD CONSTRAINT "FK_PLANNER_BOARD_P_NO" FOREIGN KEY ("PB_P_NO")
	  REFERENCES "ADMIN"."TMI_PLANNER" ("P_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD" ADD CONSTRAINT "FK_PLANNER_BOARD_M_EMAIL" FOREIGN KEY ("PB_M_EMAIL")
	  REFERENCES "ADMIN"."TMI_MEMBER" ("M_EMAIL") ON DELETE CASCADE ENABLE;
