--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-18-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_PLANNER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_PLANNER" 
   (	"P_NO" NUMBER, 
	"P_M_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"P_TITLE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"P_EXPLAN" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"P_LEAVE_DATE" DATE, 
	"P_RETURN_DATE" DATE, 
	"P_WRITE_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.TMI_PLANNER
SET DEFINE OFF;
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (301,'ym1234@naver.com','2','1',to_date('22/08/02','RR/MM/DD'),to_date('22/08/04','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (272,'ym1234@naver.com','테스트 일정',null,to_date('22/09/01','RR/MM/DD'),to_date('22/09/05','RR/MM/DD'),to_date('22/08/15','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (300,'ym1234@naver.com','ㅅ','1',to_date('22/08/05','RR/MM/DD'),to_date('22/08/07','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (302,'ym1234@naver.com','ㅋㄴㅇㅁㄴ',null,to_date('22/08/02','RR/MM/DD'),to_date('22/08/05','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (303,'ym1234@naver.com','test',null,to_date('22/08/03','RR/MM/DD'),to_date('22/08/05','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (304,'ym1234@naver.com','ㅇㅁㄴㅇㅁ',null,to_date('22/08/03','RR/MM/DD'),to_date('22/08/04','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (278,'ym1234@naver.com','test',null,to_date('22/08/01','RR/MM/DD'),to_date('22/08/03','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (298,'ym1234@naver.com','ㅅㄷㄴㅅ',null,to_date('22/08/03','RR/MM/DD'),to_date('22/08/11','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (299,'ym1234@naver.com','1',null,to_date('22/08/02','RR/MM/DD'),to_date('22/08/05','RR/MM/DD'),to_date('22/08/16','RR/MM/DD'));
Insert into ADMIN.TMI_PLANNER (P_NO,P_M_EMAIL,P_TITLE,P_EXPLAN,P_LEAVE_DATE,P_RETURN_DATE,P_WRITE_DATE) values (305,'honggd@naver.com','asd','asd',to_date('22/08/17','RR/MM/DD'),to_date('22/08/19','RR/MM/DD'),to_date('22/08/17','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_P_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_P_NO" ON "ADMIN"."TMI_PLANNER" ("P_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_PLANNER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_PLANNER" MODIFY ("P_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER" MODIFY ("P_M_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER" MODIFY ("P_TITLE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER" MODIFY ("P_LEAVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER" MODIFY ("P_RETURN_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER" ADD CONSTRAINT "PK_P_NO" PRIMARY KEY ("P_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_PLANNER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_PLANNER" ADD CONSTRAINT "FK_PLANNER_M_EMAIL" FOREIGN KEY ("P_M_EMAIL")
	  REFERENCES "ADMIN"."TMI_MEMBER" ("M_EMAIL") ON DELETE CASCADE ENABLE;
