--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-26-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_REVIEW_BOARD_LOVE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_REVIEW_BOARD_LOVE" 
   (	"RBL_NO" NUMBER, 
	"RBL_RB_NO" NUMBER, 
	"RBL_M_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"RBL_TYPE" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.TMI_REVIEW_BOARD_LOVE
SET DEFINE OFF;
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (109,67,'TMI@gmail.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (115,87,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (85,66,'ks1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (86,67,'ks1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (87,66,'honggd@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (88,65,'honggd@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (89,64,'honggd@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (90,63,'honggd@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (91,65,'ks1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (92,64,'ks1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (93,63,'ks1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (94,67,'ym1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (84,67,'honggd@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (95,66,'ym1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (96,65,'ym1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (97,64,'ym1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (98,63,'ym1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (99,67,'admin@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (100,66,'admin@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (101,65,'admin@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (102,64,'admin@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (103,63,'admin@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (104,67,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (105,66,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (106,65,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (107,64,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (108,63,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (116,88,'TMI@gmail.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (117,87,'TMI@gmail.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (120,76,'TMI@gmail.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (113,88,'admin@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (114,76,'admin@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (118,88,'cat1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (119,76,'cat1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (124,88,'susu@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (126,82,'susu@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (127,76,'susu@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (112,88,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (121,76,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (122,88,'munji@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (123,76,'munji@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (125,88,'mj1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (128,82,'munji@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (129,82,'mj1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (130,88,'bsj1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (131,82,'bsj1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (132,76,'mj1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (133,82,'ys1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (134,82,'tan1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (135,82,'danji@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (136,88,'danji@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (110,61,'ks1234@naver.com',1);
Insert into ADMIN.TMI_REVIEW_BOARD_LOVE (RBL_NO,RBL_RB_NO,RBL_M_EMAIL,RBL_TYPE) values (111,71,'honggd@naver.com',1);
--------------------------------------------------------
--  DDL for Index PK_RBL_LOVE_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_RBL_LOVE_NO" ON "ADMIN"."TMI_REVIEW_BOARD_LOVE" ("RBL_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_REVIEW_BOARD_LOVE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_REVIEW_BOARD_LOVE" MODIFY ("RBL_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_REVIEW_BOARD_LOVE" MODIFY ("RBL_M_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_REVIEW_BOARD_LOVE" ADD CONSTRAINT "PK_RBL_LOVE_NO" PRIMARY KEY ("RBL_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_REVIEW_BOARD_LOVE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_REVIEW_BOARD_LOVE" ADD CONSTRAINT "FK_REVIEW_BOARD_LOVE_RB_NO" FOREIGN KEY ("RBL_RB_NO")
	  REFERENCES "ADMIN"."TMI_REVIEW_BOARD" ("RB_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMIN"."TMI_REVIEW_BOARD_LOVE" ADD CONSTRAINT "FK_REVIEW_BOARD_LOVE_M_EMAIL" FOREIGN KEY ("RBL_M_EMAIL")
	  REFERENCES "ADMIN"."TMI_MEMBER" ("M_EMAIL") ON DELETE CASCADE ENABLE;
