--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-18-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_CHAT_CONTENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_CHAT_CONTENT" 
   (	"CONTENT_NO" NUMBER, 
	"CHATROOM_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SEND_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"RECEIVE_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE_CONTENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE_TIME" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.TMI_CHAT_CONTENT
SET DEFINE OFF;
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (101,'WizN3xSK','admin@naver.com','ys1234@naver.com','aaaaaaaaaa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (102,'WizN3xSK','admin@naver.com','ys1234@naver.com','sadadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (103,'WizN3xSK','admin@naver.com','ys1234@naver.com','asdasdas',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (104,'WizN3xSK','ys1234@naver.com','admin@naver.com','asdasdaadsads',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (105,'WizN3xSK','ys1234@naver.com','admin@naver.com','asdasdasasdasd',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (106,'WizN3xSK','admin@naver.com','ys1234@naver.com','asdasdasd',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (107,'WizN3xSK','admin@naver.com','ys1234@naver.com','asdadasd',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (108,'WizN3xSK','ys1234@naver.com','admin@naver.com','asdadadas',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (109,'6etYO2E4','ym1234@naver.com','ys1234@naver.com','zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (110,'6etYO2E4','ym1234@naver.com','ys1234@naver.com','최근메세지',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (111,'6Q0j1m1e','jdh1234@naver.com','ys1234@naver.com','adadsadasdsadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (56,'M4785A08','ys1234@naver.com','honggd@naver.com','sdaddsadasd',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (57,'M4785A08','ys1234@naver.com','honggd@naver.com','dsadsdsaa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (58,'M4785A08','ys1234@naver.com','honggd@naver.com','asdsadasdsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (59,'M4785A08','ys1234@naver.com','honggd@naver.com','asdsadadads',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (60,'M4785A08','ys1234@naver.com','honggd@naver.com','asdadasdad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (61,'M4785A08','ys1234@naver.com','honggd@naver.com','dsadasdsadsadsadsadsadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (62,'M4785A08','ys1234@naver.com','honggd@naver.com','asdads',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (63,'M4785A08','ys1234@naver.com','honggd@naver.com','asdadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (64,'M4785A08','ys1234@naver.com','honggd@naver.com','asdadsada',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (65,'M4785A08','honggd@naver.com','ys1234@naver.com','??',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (66,'M4785A08','ys1234@naver.com','honggd@naver.com','zzzzzasdas',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (67,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (70,'M4785A08','ys1234@naver.com','honggd@naver.com','asdsada',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (71,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadsadad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (72,'M4785A08','honggd@naver.com','ys1234@naver.com','asdsadas',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (73,'M4785A08','honggd@naver.com','ys1234@naver.com','asdsadadsadsada',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (74,'M4785A08','ys1234@naver.com','honggd@naver.com','asdsdsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (75,'M4785A08','honggd@naver.com','ys1234@naver.com','1234321321321',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (76,'M4785A08','honggd@naver.com','ys1234@naver.com','asdsadsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (77,'M4785A08','honggd@naver.com','ys1234@naver.com','sadadsadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (78,'M4785A08','ys1234@naver.com','honggd@naver.com','asdadsadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (79,'M4785A08','ys1234@naver.com','honggd@naver.com','asdadada',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (80,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadsadsadsadsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (81,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadsadsadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (82,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadsadsada',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (83,'M4785A08','honggd@naver.com','ys1234@naver.com','asdsada',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (84,'M4785A08','ys1234@naver.com','honggd@naver.com','asdasdsadsadadada',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (85,'M4785A08','ys1234@naver.com','honggd@naver.com','asdsadsadsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (86,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadadad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (87,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadadsadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (88,'M4785A08','ys1234@naver.com','honggd@naver.com','saddadsadada',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (89,'M4785A08','ys1234@naver.com','honggd@naver.com','asdadsadsadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (90,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadadad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (91,'M4785A08','ys1234@naver.com','honggd@naver.com','asdsadsadsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (92,'M4785A08','ys1234@naver.com','honggd@naver.com','asdasdsadsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (51,'M4785A08','ys1234@naver.com','honggd@naver.com','sdasadsadsadsadsadas',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (52,'M4785A08','ys1234@naver.com','honggd@naver.com','zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (68,'M4785A08','ys1234@naver.com','honggd@naver.com','ㅇㅁㄴㅁㄴㅇㅁㅇㄴ',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (69,'M4785A08','ys1234@naver.com','honggd@naver.com','ㅁㄴㅇㅁㄴㅇㅇ',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (53,'M4785A08','ys1234@naver.com','honggd@naver.com','asdsadasdadsadsadsad',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (54,'M4785A08','honggd@naver.com','ys1234@naver.com','asdadsadsadadsa',to_date('22/08/17','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (55,'M4785A08','honggd@naver.com','ys1234@naver.com','dadsdasdsadasdasdsa',to_date('22/08/17','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_CHAT_CONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_CHAT_CONTENT" ON "ADMIN"."TMI_CHAT_CONTENT" ("CONTENT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_CHAT_CONTENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" MODIFY ("CONTENT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" MODIFY ("CHATROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" MODIFY ("SEND_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" MODIFY ("RECEIVE_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" ADD CONSTRAINT "PK_CHAT_CONTENT" PRIMARY KEY ("CONTENT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_CHAT_CONTENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" ADD CONSTRAINT "FK_CHAT_CONTENT_CHATROOM_ID" FOREIGN KEY ("CHATROOM_ID")
	  REFERENCES "ADMIN"."TMI_CHAT_ROOM" ("CHATROOM_ID") ON DELETE CASCADE ENABLE;
