--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-26-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_PLANNER_BOARD_LOVE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_PLANNER_BOARD_LOVE" 
   (	"PBL_NO" NUMBER, 
	"PBL_M_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"PBL_PB_NO" NUMBER, 
	"PBL_TYPE" NUMBER DEFAULT '0'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.TMI_PLANNER_BOARD_LOVE
SET DEFINE OFF;
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (41,'TMI@gmail.com',63,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (86,'TMI@gmail.com',72,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (66,'mj1234@naver.com',67,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (72,'admin@naver.com',67,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (89,'TMI@gmail.com',67,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (63,'honggd@naver.com',67,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (85,'cat1234@naver.com',67,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (77,'ym1234@naver.com',73,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (78,'ym1234@naver.com',72,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (83,'cat1234@naver.com',73,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (84,'cat1234@naver.com',72,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (75,'ys1234@naver.com',73,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (76,'ys1234@naver.com',72,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (21,'honggd@naver.com',63,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (81,'tan1234@naver.com',73,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (24,'honggd@naver.com',33,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (25,'ks1234@naver.com',63,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (82,'tan1234@naver.com',72,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (87,'munji@naver.com',73,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (28,'ks1234@naver.com',33,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (29,'admin@naver.com',63,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (88,'munji@naver.com',72,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (32,'admin@naver.com',33,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (33,'ym1234@naver.com',63,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (36,'ym1234@naver.com',33,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (37,'ys1234@naver.com',63,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (40,'ys1234@naver.com',33,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (61,'ys1234@naver.com',67,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (65,'bsj1234@naver.com',67,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (69,'tan1234@naver.com',67,1);
Insert into ADMIN.TMI_PLANNER_BOARD_LOVE (PBL_NO,PBL_M_EMAIL,PBL_PB_NO,PBL_TYPE) values (74,'munji@naver.com',67,1);
--------------------------------------------------------
--  DDL for Index PK_PBL_LOVE_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_PBL_LOVE_NO" ON "ADMIN"."TMI_PLANNER_BOARD_LOVE" ("PBL_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_PLANNER_BOARD_LOVE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD_LOVE" MODIFY ("PBL_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD_LOVE" MODIFY ("PBL_M_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD_LOVE" ADD CONSTRAINT "PK_PBL_LOVE_NO" PRIMARY KEY ("PBL_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_PLANNER_BOARD_LOVE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD_LOVE" ADD CONSTRAINT "FK_PLANNER_BOARD_LOVE_PB_NO" FOREIGN KEY ("PBL_PB_NO")
	  REFERENCES "ADMIN"."TMI_PLANNER_BOARD" ("PB_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMIN"."TMI_PLANNER_BOARD_LOVE" ADD CONSTRAINT "FK_PLANNER_BOARD_LOVE_M_EMAIL" FOREIGN KEY ("PBL_M_EMAIL")
	  REFERENCES "ADMIN"."TMI_MEMBER" ("M_EMAIL") ON DELETE CASCADE ENABLE;
