--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-18-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_FRIEND_BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_FRIEND_BOARD_COMMENT" 
   (	"FBC_NO" NUMBER, 
	"FBC_M_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"FBC_FB_NO" NUMBER, 
	"FBC_CREATED_AT" DATE DEFAULT sysdate, 
	"FBC_CONTENT" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.TMI_FRIEND_BOARD_COMMENT
SET DEFINE OFF;
Insert into ADMIN.TMI_FRIEND_BOARD_COMMENT (FBC_NO,FBC_M_EMAIL,FBC_FB_NO,FBC_CREATED_AT,FBC_CONTENT) values (30,'honggd@naver.com',139,to_date('22/08/13','RR/MM/DD'),'테스트');
Insert into ADMIN.TMI_FRIEND_BOARD_COMMENT (FBC_NO,FBC_M_EMAIL,FBC_FB_NO,FBC_CREATED_AT,FBC_CONTENT) values (24,'honggd@naver.com',139,to_date('22/08/13','RR/MM/DD'),'테스트');
Insert into ADMIN.TMI_FRIEND_BOARD_COMMENT (FBC_NO,FBC_M_EMAIL,FBC_FB_NO,FBC_CREATED_AT,FBC_CONTENT) values (1,'honggd@naver.com',145,to_date('22/08/11','RR/MM/DD'),'댓글 테스트');
Insert into ADMIN.TMI_FRIEND_BOARD_COMMENT (FBC_NO,FBC_M_EMAIL,FBC_FB_NO,FBC_CREATED_AT,FBC_CONTENT) values (21,'honggd@naver.com',145,to_date('22/08/13','RR/MM/DD'),'테스트');
Insert into ADMIN.TMI_FRIEND_BOARD_COMMENT (FBC_NO,FBC_M_EMAIL,FBC_FB_NO,FBC_CREATED_AT,FBC_CONTENT) values (31,'honggd@naver.com',145,to_date('22/08/13','RR/MM/DD'),'댓글 테스트');
--------------------------------------------------------
--  DDL for Index PK_FBC_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_FBC_NO" ON "ADMIN"."TMI_FRIEND_BOARD_COMMENT" ("FBC_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_FRIEND_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_FRIEND_BOARD_COMMENT" MODIFY ("FBC_M_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_FRIEND_BOARD_COMMENT" ADD CONSTRAINT "PK_FBC_NO" PRIMARY KEY ("FBC_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_FRIEND_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_FRIEND_BOARD_COMMENT" ADD CONSTRAINT "FK_PLANNER_FRIEND_COMENT_RB_NO" FOREIGN KEY ("FBC_FB_NO")
	  REFERENCES "ADMIN"."TMI_FRIEND_BOARD" ("FB_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMIN"."TMI_FRIEND_BOARD_COMMENT" ADD CONSTRAINT "FK_PLANNER_FRIEND_M_EMAIL" FOREIGN KEY ("FBC_M_EMAIL")
	  REFERENCES "ADMIN"."TMI_MEMBER" ("M_EMAIL") ON DELETE CASCADE ENABLE;
