--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-26-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_NOTICE_BOARD
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_NOTICE_BOARD" 
   (	"NB_NO" NUMBER, 
	"NB_M_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"NB_TITLE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"NB_CREATED_AT" DATE DEFAULT sysdate, 
	"NB_UPDATE_AT" DATE DEFAULT sysdate, 
	"NB_READ_COUNT" NUMBER DEFAULT 0, 
	"NB_CONTENT" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("NB_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ADMIN.TMI_NOTICE_BOARD
SET DEFINE OFF;
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (75,'admin@naver.com','123',to_date('22/08/25','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),2);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (28,'admin@naver.com',null,to_date('22/08/19','RR/MM/DD'),to_date('22/08/19','RR/MM/DD'),1);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (24,'admin@naver.com',null,to_date('22/08/19','RR/MM/DD'),to_date('22/08/21','RR/MM/DD'),2);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (53,'admin@naver.com','도로사진',to_date('22/08/21','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),6);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (68,'admin@naver.com','1',to_date('22/08/24','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),3);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (70,'admin@naver.com','3',to_date('22/08/24','RR/MM/DD'),to_date('22/08/24','RR/MM/DD'),3);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (71,'admin@naver.com','4',to_date('22/08/24','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),3);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (54,'admin@naver.com','공지사항입니다.',to_date('22/08/21','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),4);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (50,'admin@naver.com','이미지ㅇㅇ',to_date('22/08/21','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),4);
Insert into ADMIN.TMI_NOTICE_BOARD (NB_NO,NB_M_EMAIL,NB_TITLE,NB_CREATED_AT,NB_UPDATE_AT,NB_READ_COUNT) values (48,'admin@naver.com','ㅇㅇ',to_date('22/08/20','RR/MM/DD'),to_date('22/08/25','RR/MM/DD'),3);
--------------------------------------------------------
--  DDL for Index PK_NB_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_NB_NO" ON "ADMIN"."TMI_NOTICE_BOARD" ("NB_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_NOTICE_BOARD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_NOTICE_BOARD" MODIFY ("NB_M_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_NOTICE_BOARD" ADD CONSTRAINT "PK_NB_NO" PRIMARY KEY ("NB_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_NOTICE_BOARD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_NOTICE_BOARD" ADD CONSTRAINT "FK_NOTICE_BOARD_M_EMAIL" FOREIGN KEY ("NB_M_EMAIL")
	  REFERENCES "ADMIN"."TMI_MEMBER" ("M_EMAIL") ON DELETE SET NULL ENABLE;
