--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-18-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_FRIEND_BOARD_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_FRIEND_BOARD_ATTACHMENT" 
   (	"FBA_NO" NUMBER, 
	"FBA_FB_NO" NUMBER, 
	"FBA_ORIGINAL_FILENAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"FBA_RENAMED_FILENAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"TBA_CREATED_AT" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT
SET DEFINE OFF;
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (41,83,'fish.png','20220808_014937607_291.png',to_date('22/08/07','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (42,84,'dog.png','20220808_015012885_272.png',to_date('22/08/07','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (43,86,'dog.png','20220808_015956206_217.png',to_date('22/08/07','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (22,21,'test.jpg','20200525_090909_123.jpg',to_date('22/08/05','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (23,22,'moon.jpg','20200525_090909_345.jpg',to_date('22/08/05','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (24,23,'sun.jpg','20200525_020425_345.jpg',to_date('22/08/05','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (46,107,'fish.png','20220809_013708754_171.png',to_date('22/08/08','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (44,87,'cat.png','20220808_150146453_216.png',to_date('22/08/08','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (45,87,'dog.png','20220808_150146454_855.png',to_date('22/08/08','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (81,143,'cat.png','20220810_230022159_906.png',to_date('22/08/10','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (82,143,'fish.png','20220810_230022160_043.png',to_date('22/08/10','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (85,145,'fish.png','20220811_023256806_004.png',to_date('22/08/10','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (86,145,'수제비 실기 요약.docx.pdf','20220811_023256808_466.pdf',to_date('22/08/10','RR/MM/DD'));
Insert into ADMIN.TMI_FRIEND_BOARD_ATTACHMENT (FBA_NO,FBA_FB_NO,FBA_ORIGINAL_FILENAME,FBA_RENAMED_FILENAME,TBA_CREATED_AT) values (89,148,'fish (1).png','20220816_013452933_649.png',to_date('22/08/15','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_FBA_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_FBA_NO" ON "ADMIN"."TMI_FRIEND_BOARD_ATTACHMENT" ("FBA_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_FRIEND_BOARD_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_FRIEND_BOARD_ATTACHMENT" MODIFY ("FBA_ORIGINAL_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_FRIEND_BOARD_ATTACHMENT" MODIFY ("FBA_RENAMED_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_FRIEND_BOARD_ATTACHMENT" ADD CONSTRAINT "PK_FBA_NO" PRIMARY KEY ("FBA_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_FRIEND_BOARD_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_FRIEND_BOARD_ATTACHMENT" ADD CONSTRAINT "FK_FRIEND_BOARD_ATTACHMENT_FB_NO" FOREIGN KEY ("FBA_FB_NO")
	  REFERENCES "ADMIN"."TMI_FRIEND_BOARD" ("FB_NO") ON DELETE CASCADE ENABLE;
