--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-26-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMI_CHAT_CONTENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TMI_CHAT_CONTENT" 
   (	"CONTENT_NO" NUMBER, 
	"CHATROOM_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SEND_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"RECEIVE_EMAIL" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE_CONTENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE_TIME" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.TMI_CHAT_CONTENT
SET DEFINE OFF;
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (65,'gecJ382r','ys1234@naver.com','honggd@naver.com','zzzz',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (124,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (114,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (115,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅁㄴㅇㅁㅇㅁㅇ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (116,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅇㅇㅇㅇ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (117,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅁㄴㅇㅁㄴㅇ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (122,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (123,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (125,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (126,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (127,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (128,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (129,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (130,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (133,'gecJ382r','honggd@naver.com','ys1234@naver.com','asdada',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (134,'gecJ382r','honggd@naver.com','ys1234@naver.com','asdadsada',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (136,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅁ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (137,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅁㄴ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (138,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㄴㅇ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (139,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅇㅁ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (140,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅁㅇ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (141,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅇㄴ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (142,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㄴㅁ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (143,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅁㅇ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (144,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅇㄴ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (145,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㄴㅇ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (146,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅇㅁ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (147,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅁㅁ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (148,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅋㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (149,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (150,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅋㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (151,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅇㅁㄴㅇㄴㅁㅇㅁㄴ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (152,'440nICD9','honggd@naver.com','ks1234@naver.com','ㄴㅁㅇㅁㄴㅇㄴㅁㅇㅁㄴㅇㅇㄴㅁ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (153,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅁㄴㅇㅁㄴㅇㄴㅁㅇㄴㅁㅁㄴㅇ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (154,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅋㅋㅋㅋ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (155,'440nICD9','honggd@naver.com','ks1234@naver.com','ㅁㄴㅇㄴㅁㅇㄴㅁ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (156,'440nICD9','honggd@naver.com','ks1234@naver.com','ㄴㄴㄴㄴ',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (157,'440nICD9','honggd@naver.com','ks1234@naver.com','아니',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (158,'440nICD9','honggd@naver.com','ks1234@naver.com','구우우웃',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (159,'440nICD9','honggd@naver.com','ks1234@naver.com','하아아아잇',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (160,'440nICD9','honggd@naver.com','ks1234@naver.com','좋아',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (161,'440nICD9','honggd@naver.com','ks1234@naver.com','굿굿',to_date('22/08/20','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (287,'47Xy0v00','ys1234@naver.com','ym1234@naver.com','ㅋㅋㅋㅋㅋㅋ',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (289,'47Xy0v00','ys1234@naver.com','ym1234@naver.com','ㅋㅋ',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (269,'gecJ382r','ys1234@naver.com','honggd@naver.com','zz',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (270,'gecJ382r','ys1234@naver.com','honggd@naver.com','di',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (273,'gecJ382r','honggd@naver.com','ys1234@naver.com','asdaqd',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (274,'gecJ382r','ys1234@naver.com','honggd@naver.com','asdsaa',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (275,'gecJ382r','honggd@naver.com','ys1234@naver.com','asdsads',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (276,'47Xy0v00','ys1234@naver.com','ym1234@naver.com','gd',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (277,'47Xy0v00','ys1234@naver.com','ym1234@naver.com','하이',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (279,'47Xy0v00','ys1234@naver.com','ym1234@naver.com','하이',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (281,'47Xy0v00','ys1234@naver.com','ym1234@naver.com','ㅁㅁㅁ',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (283,'47Xy0v00','ys1234@naver.com','ym1234@naver.com','ㄴㄴ',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (271,'gecJ382r','honggd@naver.com','ys1234@naver.com','ss',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (272,'gecJ382r','ys1234@naver.com','honggd@naver.com','asdasd',to_date('22/08/25','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (66,'gecJ382r','ys1234@naver.com','honggd@naver.com','야',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (67,'gecJ382r','honggd@naver.com','ys1234@naver.com','왜',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (68,'gecJ382r','ys1234@naver.com','honggd@naver.com','뭐냐',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (69,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (70,'gecJ382r','ys1234@naver.com','honggd@naver.com','ㅋㅋㅋㅋ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (71,'gecJ382r','ys1234@naver.com','honggd@naver.com','ㅋㅋㅋㅋ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (72,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋㅋㅋ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (73,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋㅋ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (74,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋㅋㅇㅋㅇㅋ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (75,'gecJ382r','ys1234@naver.com','honggd@naver.com','뭔데',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (76,'gecJ382r','honggd@naver.com','ys1234@naver.com','ㅋㅋ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (98,'gecJ382r','honggd@naver.com','ys1234@naver.com','ggzdzasddsasad',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (2,'gecJ382r','ys1234@naver.com','honggd@naver.com','sddss',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (3,'gecJ382r','ys1234@naver.com','honggd@naver.com','dsadasdsaadsasd',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (4,'gecJ382r','ys1234@naver.com','honggd@naver.com','하아ㅣㅣ아니암',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (5,'gecJ382r','ys1234@naver.com','honggd@naver.com','안녕',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (6,'gecJ382r','ys1234@naver.com','honggd@naver.com','ㄴㅇㅁㅇㄴ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (14,'gecJ382r','ys1234@naver.com','honggd@naver.com','그럼이제 됌"?',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (15,'gecJ382r','ys1234@naver.com','honggd@naver.com','이렇게 보낼때',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (16,'gecJ382r','ys1234@naver.com','honggd@naver.com','ㅁㄹ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (17,'gecJ382r','ys1234@naver.com','honggd@naver.com','ㅁㅋㅋㅋ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (18,'gecJ382r','ys1234@naver.com','honggd@naver.com','ㅇㅇㅇ',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (24,'gecJ382r','ys1234@naver.com','honggd@naver.com','zzzzzzzzzzzzzz',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (26,'gecJ382r','ys1234@naver.com','honggd@naver.com','zzz',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (29,'gecJ382r','ys1234@naver.com','honggd@naver.com','zzz',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (31,'gecJ382r','ys1234@naver.com','honggd@naver.com','zzzzz',to_date('22/08/19','RR/MM/DD'));
Insert into ADMIN.TMI_CHAT_CONTENT (CONTENT_NO,CHATROOM_ID,SEND_EMAIL,RECEIVE_EMAIL,MESSAGE_CONTENT,MESSAGE_TIME) values (32,'gecJ382r','ys1234@naver.com','honggd@naver.com','왜 바로바로 출력이 안돼는거야',to_date('22/08/19','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_CHAT_CONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_CHAT_CONTENT" ON "ADMIN"."TMI_CHAT_CONTENT" ("CONTENT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TMI_CHAT_CONTENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" MODIFY ("CONTENT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" MODIFY ("CHATROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" MODIFY ("SEND_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" MODIFY ("RECEIVE_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" ADD CONSTRAINT "PK_CHAT_CONTENT" PRIMARY KEY ("CONTENT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TMI_CHAT_CONTENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TMI_CHAT_CONTENT" ADD CONSTRAINT "FK_CHAT_CONTENT_CHATROOM_ID" FOREIGN KEY ("CHATROOM_ID")
	  REFERENCES "ADMIN"."TMI_CHAT_ROOM" ("CHATROOM_ID") ON DELETE CASCADE ENABLE;
